<?php

/**
 * Implementation of BNBBeaconChain API
 *
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto generated by tatum.io
 * Do not edit this file manually
 */

namespace Tatum\Api;

use InvalidArgumentException as IAE;
use Tatum\Sdk\ApiException as APIE;
use Tatum\Sdk\Serializer as S;

/**
 * BNBBeaconChain API
 */
class BNBBeaconChainApi extends AbstractApi {
    /**
     * Send Binance / Binance Token from account to account
     *
     * @param \Tatum\Model\BnbBlockchainTransferRequest $bnb_blockchain_transfer_request 
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Tatum\Model\TransactionHash
     */
    public function bnbBlockchainTransfer(\Tatum\Model\BnbBlockchainTransferRequest $bnb_blockchain_transfer_request) {
        $rPath = "/v3/bnb/transaction";
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], ["application/json"]);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "POST", $rPath, [], $rHeaders, [], $bnb_blockchain_transfer_request
            ), 
            "\Tatum\Model\TransactionHash"
        );
    }
    
    /**
     * Broadcast signed BNB transaction
     *
     * @param \Tatum\Model\Broadcast $broadcast 
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Tatum\Model\TransactionHash
     */
    public function bnbBroadcast(\Tatum\Model\Broadcast $broadcast) {
        $rPath = "/v3/bnb/broadcast";
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], ["application/json"]);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "POST", $rPath, [], $rHeaders, [], $broadcast
            ), 
            "\Tatum\Model\TransactionHash"
        );
    }
    
    /**
     * Generate Binance wallet
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Tatum\Model\BnbWallet
     */
    public function bnbGenerateWallet() {
        $rPath = "/v3/bnb/account";
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "GET", $rPath, [], $rHeaders, []
            ), 
            "\Tatum\Model\BnbWallet"
        );
    }
    
    /**
     * Get Binance Account
     *
     * @param string $address Account address you want to get balance of
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Tatum\Model\BnbAccount
     */
    public function bnbGetAccount(string $address) {
        $rPath = "/v3/bnb/account/{address}";
        $rPath = str_replace("{"."address"."}", S::toPathValue($address), $rPath);
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "GET", $rPath, [], $rHeaders, []
            ), 
            "\Tatum\Model\BnbAccount"
        );
    }
    
    /**
     * Get Binance Transactions in Block
     *
     * @param float $height Block height
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Tatum\Model\BnbBlock
     */
    public function bnbGetBlock(float $height) {
        $rPath = "/v3/bnb/block/{height}";
        $rPath = str_replace("{"."height"."}", S::toPathValue($height), $rPath);
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "GET", $rPath, [], $rHeaders, []
            ), 
            "\Tatum\Model\BnbBlock"
        );
    }
    
    /**
     * Get Binance current block
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return float
     */
    public function bnbGetCurrentBlock() {
        $rPath = "/v3/bnb/block/current";
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "GET", $rPath, [], $rHeaders, []
            ), 
            "float"
        );
    }
    
    /**
     * Get Binance Transaction
     *
     * @param string $hash Transaction hash
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Tatum\Model\BnbTx
     */
    public function bnbGetTransaction(string $hash) {
        $rPath = "/v3/bnb/transaction/{hash}";
        $rPath = str_replace("{"."hash"."}", S::toPathValue($hash), $rPath);
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "GET", $rPath, [], $rHeaders, []
            ), 
            "\Tatum\Model\BnbTx"
        );
    }
    
    /**
     * Get Binance Transactions By Address
     *
     * @param string $address Account address
     * @param float $start_time Start time in milliseconds
     * @param float $end_time End time in milliseconds
     * @param float|null $limit Items per page.
     * @param float|null $offset Pagination offset
     * @param string|null $asset Asset name
     * @param string|null $address_type Address type
     * @throws \Tatum\Sdk\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * 
     * @return \Tatum\Model\BnbTxInAccount
     */
    public function bnbGetTxByAccount(string $address, float $start_time, float $end_time, float $limit = null, float $offset = null, string $asset = null, string $address_type = null) {
        if ($start_time < 0) {
            throw new IAE('Invalid value for "$start_time" when calling BNBBeaconChainApi.bnbGetTxByAccount, must be bigger than or equal to 0.');
        }

        if ($end_time < 0) {
            throw new IAE('Invalid value for "$end_time" when calling BNBBeaconChainApi.bnbGetTxByAccount, must be bigger than or equal to 0.');
        }

        if (isset($limit) && $limit > 50) {
            throw new IAE('Invalid value for "$limit" when calling BNBBeaconChainApi.bnbGetTxByAccount, must be smaller than or equal to 50');
        }

        if (isset($limit) && $limit < 1) {
            throw new IAE('Invalid value for "$limit" when calling BNBBeaconChainApi.bnbGetTxByAccount, must be bigger than or equal to 1.');
        }

        if (isset($offset) && $offset < 0) {
            throw new IAE('Invalid value for "$offset" when calling BNBBeaconChainApi.bnbGetTxByAccount, must be bigger than or equal to 0.');
        }

        $rPath = "/v3/bnb/account/transaction/{address}";
        $rPath = str_replace("{"."address"."}", S::toPathValue($address), $rPath);
        $rHeaders = $this->_headerSelector->selectHeaders(["application/json"], []);

        return $this->exec(
            S::createRequest(
                $this->_caller->config(), "GET", $rPath, [
                    "startTime" => S::toQueryValue($start_time),
                
                    "endTime" => S::toQueryValue($end_time),
                
                    "limit" => isset($limit) ? S::toQueryValue($limit) : null,
                
                    "offset" => isset($offset) ? S::toQueryValue($offset) : null,
                
                    "asset" => isset($asset) ? S::toQueryValue($asset) : null,
                
                    "addressType" => isset($address_type) ? S::toQueryValue($address_type) : null,
                ], $rHeaders, []
            ), 
            "\Tatum\Model\BnbTxInAccount"
        );
    }
    
}
