<?php

/**
 * AlgoNodePostDriver_200_response Model
 *
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto-generated by tatum.io
 * Do not edit this file manually!
 */

namespace Tatum\Model;
!defined("TATUM-SDK") && exit();

/**
 * AlgoNodePostDriver_200_response Model
 */
class AlgoNodePostDriver200Response extends AbstractModel {

    public const _D = null;
    protected static $_name = "AlgoNodePostDriver_200_response";
    protected static $_definition = [
        "tx_id" => ["txId", "string", null, "getTxId", "setTxId", null, ["r" => 0]]
    ];

    /**
     * AlgoNodePostDriver200Response
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get tx_id
     *
     * @return string|null
     */
    public function getTxId(): ?string {
        return $this->_data["tx_id"];
    }

    /**
     * Set tx_id
     * 
     * @param string|null $tx_id Check here - <a href=\"https://developer.algorand.org/docs/rest-apis/algod/v2/#rawtransaction-response-200\" target=\"_blank\">https://developer.algorand.org/docs/rest-apis/algod/v2/#rawtransaction-response-200</a>
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setTxId(?string $tx_id) {
        return $this->_set("tx_id", $tx_id);
    }
}
