<?php

/**
 * Consumption Model
 *
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto-generated by tatum.io
 * Do not edit this file manually!
 */

namespace Tatum\Model;
!defined("TATUM-SDK") && exit();

/**
 * Consumption Model
 */
class Consumption extends AbstractModel {

    public const _D = null;
    protected static $_name = "Consumption";
    protected static $_definition = [
        "day" => ["day", "string", null, "getDay", "setDay", null, ["r" => 0]], 
        "usage" => ["usage", "float", null, "getUsage", "setUsage", null, ["r" => 0]]
    ];

    /**
     * Consumption
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get day
     *
     * @return string|null
     */
    public function getDay(): ?string {
        return $this->_data["day"];
    }

    /**
     * Set day
     * 
     * @param string|null $day The date in the MM/DD/YYYY format
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setDay(?string $day) {
        return $this->_set("day", $day);
    }

    /**
     * Get usage
     *
     * @return float|null
     */
    public function getUsage(): ?float {
        return $this->_data["usage"];
    }

    /**
     * Set usage
     * 
     * @param float|null $usage The number of credits used on the specified day
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setUsage(?float $usage) {
        return $this->_set("usage", $usage);
    }
}
