<?php

/**
 * FlowCustomTransactionPK_args_inner_value Model
 *
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto generated by tatum.io
 * Do not edit this file manually
 */

namespace Tatum\Model;

use InvalidArgumentException as IAE;

/**
 * FlowCustomTransactionPK_args_inner_value Model
 * 
 * @description The value of the argument; can be a string or an array of strings
 */
class FlowCustomTransactionPKArgsInnerValue extends AbstractModel {

    public const DISCRIMINATOR = null;
    protected static $_name = "FlowCustomTransactionPK_args_inner_value";
    protected static $_definition = [
    ];

    /**
     * FlowCustomTransactionPKArgsInnerValue
     */
    public function __construct() {
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array {
        $ip = [];

        
        return $ip;
    }
}
