<?php

/**
 * SolanaBlock_transactions_inner_transaction_message Model
 *
 * @version   3.17.0
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto generated by tatum.io
 * Do not edit this file manually
 */

namespace Tatum\Model;

use InvalidArgumentException as IAE;

/**
 * SolanaBlock_transactions_inner_transaction_message Model
 */
class SolanaBlockTransactionsInnerTransactionMessage extends AbstractModel {

    public const DISCRIMINATOR = null;
    protected static $_name = "SolanaBlock_transactions_inner_transaction_message";
    protected static $_definition = [
        "header" => ["header", "\Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageHeader", null, "getHeader", "setHeader"], 
        "account_keys" => ["accountKeys", "\Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageAccountKeysInner[]", null, "getAccountKeys", "setAccountKeys"], 
        "recent_blockhash" => ["recentBlockhash", "string", null, "getRecentBlockhash", "setRecentBlockhash"], 
        "instructions" => ["instructions", "\Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageInstructionsInner[]", null, "getInstructions", "setInstructions"], 
        "index_to_program_ids" => ["indexToProgramIds", "object", null, "getIndexToProgramIds", "setIndexToProgramIds"]
    ];

    /**
     * SolanaBlockTransactionsInnerTransactionMessage
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(["header"=>null, "account_keys"=>null, "recent_blockhash"=>null, "instructions"=>null, "index_to_program_ids"=>null] as $k => $v) {
            $this->_data[$k] = $data[$k] ?? $v;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array {
        $ip = [];

        
        return $ip;
    }

    /**
     * Get header
     *
     * @return \Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageHeader|null
     */
    public function getHeader(): ?\Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageHeader {
        return $this->_data["header"];
    }

    /**
     * Set header
     * 
     * @param \Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageHeader|null $header header
     * @return $this
     */
    public function setHeader(?\Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageHeader $header) {
        $this->_data['header'] = $header;

        return $this;
    }

    /**
     * Get account_keys
     *
     * @return \Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageAccountKeysInner[]|null
     */
    public function getAccountKeys(): ?array {
        return $this->_data["account_keys"];
    }

    /**
     * Set account_keys
     * 
     * @param \Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageAccountKeysInner[]|null $account_keys account_keys
     * @return $this
     */
    public function setAccountKeys(?array $account_keys) {
        $this->_data['account_keys'] = $account_keys;

        return $this;
    }

    /**
     * Get recent_blockhash
     *
     * @return string|null
     */
    public function getRecentBlockhash(): ?string {
        return $this->_data["recent_blockhash"];
    }

    /**
     * Set recent_blockhash
     * 
     * @param string|null $recent_blockhash recent_blockhash
     * @return $this
     */
    public function setRecentBlockhash(?string $recent_blockhash) {
        $this->_data['recent_blockhash'] = $recent_blockhash;

        return $this;
    }

    /**
     * Get instructions
     *
     * @return \Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageInstructionsInner[]|null
     */
    public function getInstructions(): ?array {
        return $this->_data["instructions"];
    }

    /**
     * Set instructions
     * 
     * @param \Tatum\Model\SolanaBlockTransactionsInnerTransactionMessageInstructionsInner[]|null $instructions instructions
     * @return $this
     */
    public function setInstructions(?array $instructions) {
        $this->_data['instructions'] = $instructions;

        return $this;
    }

    /**
     * Get index_to_program_ids
     *
     * @return object|null
     */
    public function getIndexToProgramIds(): ?object {
        return $this->_data["index_to_program_ids"];
    }

    /**
     * Set index_to_program_ids
     * 
     * @param object|null $index_to_program_ids index_to_program_ids
     * @return $this
     */
    public function setIndexToProgramIds(?object $index_to_program_ids) {
        $this->_data['index_to_program_ids'] = $index_to_program_ids;

        return $this;
    }
}
