<?php

/**
 * SolanaTxTransaction Model
 *
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto-generated by tatum.io
 * Do not edit this file manually!
 */

namespace Tatum\Model;
!defined("TATUM-SDK") && exit();

/**
 * SolanaTxTransaction Model
 */
class SolanaTxTransaction extends AbstractModel {

    public const _D = null;
    protected static $_name = "SolanaTxTransaction";
    protected static $_definition = [
        "message" => ["message", "\Tatum\Model\SolanaTxMessage", null, "getMessage", "setMessage", null, ["r" => 0]], 
        "signatures" => ["signatures", "string[]", null, "getSignatures", "setSignatures", null, ["r" => 0, "c" => 1]]
    ];

    /**
     * SolanaTxTransaction
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }


    /**
     * Get message
     *
     * @return \Tatum\Model\SolanaTxMessage|null
     */
    public function getMessage(): ?\Tatum\Model\SolanaTxMessage {
        return $this->_data["message"];
    }

    /**
     * Set message
     * 
     * @param \Tatum\Model\SolanaTxMessage|null $message message
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setMessage(?\Tatum\Model\SolanaTxMessage $message) {
        return $this->_set("message", $message);
    }

    /**
     * Get signatures
     *
     * @return string[]|null
     */
    public function getSignatures(): ?array {
        return $this->_data["signatures"];
    }

    /**
     * Set signatures
     * 
     * @param string[]|null $signatures signatures
     * @throws \InvalidArgumentException
     * @return $this
     */
    public function setSignatures(?array $signatures) {
        return $this->_set("signatures", $signatures);
    }
}
