<?php

/**
 * VetTxReceipt_outputs_inner_transfers_inner Model
 *
 * @version   3.17.1
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto generated by tatum.io
 * Do not edit this file manually
 */

namespace Tatum\Model;

use InvalidArgumentException as IAE;

/**
 * VetTxReceipt_outputs_inner_transfers_inner Model
 */
class VetTxReceiptOutputsInnerTransfersInner extends AbstractModel {

    public const DISCRIMINATOR = null;
    protected static $_name = "VetTxReceipt_outputs_inner_transfers_inner";
    protected static $_definition = [
        "sender" => ["sender", "string", null, "getSender", "setSender"], 
        "recipient" => ["recipient", "string", null, "getRecipient", "setRecipient"], 
        "amount" => ["amount", "string", null, "getAmount", "setAmount"]
    ];

    /**
     * VetTxReceiptOutputsInnerTransfersInner
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(["sender"=>null, "recipient"=>null, "amount"=>null] as $k => $v) {
            $this->_data[$k] = $data[$k] ?? $v;
        }
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array {
        $ip = [];

        
        return $ip;
    }

    /**
     * Get sender
     *
     * @return string|null
     */
    public function getSender(): ?string {
        return $this->_data["sender"];
    }

    /**
     * Set sender
     * 
     * @param string|null $sender sender
     * @return $this
     */
    public function setSender(?string $sender) {
        $this->_data['sender'] = $sender;

        return $this;
    }

    /**
     * Get recipient
     *
     * @return string|null
     */
    public function getRecipient(): ?string {
        return $this->_data["recipient"];
    }

    /**
     * Set recipient
     * 
     * @param string|null $recipient recipient
     * @return $this
     */
    public function setRecipient(?string $recipient) {
        $this->_data['recipient'] = $recipient;

        return $this;
    }

    /**
     * Get amount
     *
     * @return string|null
     */
    public function getAmount(): ?string {
        return $this->_data["amount"];
    }

    /**
     * Set amount
     * 
     * @param string|null $amount amount
     * @return $this
     */
    public function setAmount(?string $amount) {
        $this->_data['amount'] = $amount;

        return $this;
    }
}
