<?php

/**
 * WithdrawalHint_value Model
 *
 * @copyright (c) 2022-2023 tatum.io
 * @license   MIT
 * @package   Tatum
 * @author    Mark Jivko
 * @link      https://tatum.io/
 *
 * NOTE: This class is auto generated by tatum.io
 * Do not edit this file manually
 */

namespace Tatum\Model;

use InvalidArgumentException as IAE;

/**
 * WithdrawalHint_value Model
 */
class WithdrawalHintValue extends AbstractModel {

    public const DISCRIMINATOR = null;
    protected static $_name = "WithdrawalHint_value";
    protected static $_definition = [
        "address" => ["address", "\Tatum\Model\Address", null, "getAddress", "setAddress", null], 
        "amount" => ["amount", "string", null, "getAmount", "setAmount", null]
    ];

    /**
     * WithdrawalHintValue
     *
     * @param mixed[] $data Model data
     */
    public function __construct(array $data = []) {
        foreach(static::$_definition as $k => $v) {
            $this->_data[$k] = isset($data[$k]) ? $data[$k] : $v[5];
        }
    }
    
    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array {
        $ip = [];
        return $ip;
    }


    /**
     * Get address
     *
     * @return \Tatum\Model\Address|null
     */
    public function getAddress(): ?\Tatum\Model\Address {
        return $this->_data["address"];
    }

    /**
     * Set address
     * 
     * @param \Tatum\Model\Address|null $address address
     * @return $this
     */
    public function setAddress(?\Tatum\Model\Address $address) {
        $this->_data['address'] = $address;

        return $this;
    }

    /**
     * Get amount
     *
     * @return string|null
     */
    public function getAmount(): ?string {
        return $this->_data["amount"];
    }

    /**
     * Set amount
     * 
     * @param string|null $amount Balance for address.
     * @return $this
     */
    public function setAmount(?string $amount) {
        $this->_data['amount'] = $amount;

        return $this;
    }
}
